### PR TITLE
Vary chi2 cut per layer/iteration/kinematics, plus add lower bound to dphi cut (hit, track candidate)

### PR DESCRIPTION
**Pull request by mmasciov**
http://uaf-10.t2.ucsd.edu/~mmasciov/MkFit_devs/SVA_varyChi2Sf1p5_fixedMinDPhi_noTR_vsBaseline/

### CODE REVIEW

**Comment by slava77** [comment]
@mmasciov 
do you have MTV plots? 10mu and ttbar would be nice; using mkFit before this PR as a reference.
Thanks.

**Comment by mmasciov** [comment]
@slava77 not yet. I will produce them.

**Comment by cerati** [comment]
@mmasciov I think it's important to see the MTV plots with CMSSW as reference as well. Thanks...

**Comment by slava77** [comment]
it would be nice to rebase this PR so that #336 does not show up in the commits/diffs

**Comment by mmasciov** [comment]
MTV results, based on the default CMSSW_11_2_0_mkFit_X branch (where all iterations make use of mkFit):
TTbar (PU50): http://uaf-10.t2.ucsd.edu/~mmasciov/MkFit_devs/MTV-PR338_ttbarPU50/
10mu: http://uaf-10.t2.ucsd.edu/~mmasciov/MkFit_devs/MTV-PR338_10mu/
For all tracks out-of-the-box (TTbar):
--> Negligible difference in efficiency and fake+duplicate rates: http://uaf-10.t2.ucsd.edu/~mmasciov/MkFit_devs/MTV-PR338_ttbarPU50/plots_ootb/effandfakePtEtaPhi.pdf
--> Increase in # hits, by ~0.3: http://uaf-10.t2.ucsd.edu/~mmasciov/MkFit_devs/MTV-PR338_ttbarPU50/plots_ootb/hitsAndPt.pdf
 --> Few % improvement in resolution (still far from CKF, as expected): http://uaf-10.t2.ucsd.edu/~mmasciov/MkFit_devs/MTV-PR338_ttbarPU50/plots_ootb/resolutionsEta.pdf

**Comment by slava77** [comment]
> MTV results:

which variant of mkFit enabled is this? the 4 iters or something else?

**Comment by mmasciov** [comment]
> which variant of mkFit enabled is this? the 4 iters or something else?

I modified the message above: MTV results are based on the default CMSSW_11_2_0_mkFit_X branch (where all iterations make use of mkFit).

**Comment by mmasciov** [comment]
Closing in favor of 'cleaner' PR #340.

**Pull request closed without merging**
