### PR TITLE
Backport of tbb cleanup

### PR DESCRIPTION
**Pull request by dan131riley**
This PR backports the TBB cleanup to the v2.0.1_patches branch in order to address issue #290 updating TBB.  The simplest way to do the backport was to merge most of the CUDA removal PR #283 and all of the FullVector removal PR #286 so besides the TBB update it also removes a lot of dead code.

There shouldn't be an change in physics or computing performance, but I'll try running validation at Cornell (the input file for this older version is no longer in place on phi3).

### CODE REVIEW

**Comment by dan131riley** [comment]
Benchmarks are [here](https://www.classe.cornell.edu/~dsr/mic-track/pr291/Benchmarks/).  These were run on lnx7188, so the CPU benchmarks may differ some, and the multiple events in flight show a known intermittent  anomaly on the first point.  Physics should be identical (and do appear to be) to the #240 [validation plots](https://areinsvo.web.cern.ch/areinsvo/MkFit/Benchmarks/PR240/standalone/).

**Comment by slava77** [comment]
considering the amount of changes, I think that this will become v2.1.0 release once merged, instead of v2.1.0-2 patch.

**Comment by slava77** [comment]
```
RecoTracker/MkFit/plugins/MkFitProducer.cc:86:41: error: no matching function for call to 'mkfit::MkBuilderWrapper::populate(bool&)'
   86 |   mkfit::MkBuilderWrapper::populate(isFV);
```
I guess it either requires a PR for CMSSW or this backport should be made more targeted to be compatible with the CMSSW release.

**Comment by makortel** [comment]
> revert interface change

I suspect that is not sufficient because of
```cpp
  } else if (build == "fullVector") {
    isFV = true;
    buildFunction_ = mkfit::runBuildingTestPlexFV;
```
in https://github.com/cms-sw/cmssw/blob/eb134e644ee5255fc0656f1e4181bfca7203306e/RecoTracker/MkFit/plugins/MkFitProducer.cc#L63-L65
We still seem to declare the function
https://github.com/trackreco/mkFit/blob/27f790c3edc96630d7c658f7d4d4b86389986488/mkFit/buildtestMPlex.h#L15
but could missing the definition lead to link failure?

**Comment by dan131riley** [comment]
Yes, it does lead to a link failure.  (I've now done the test build with CMSSW that I should have before making the PR.)

**Comment by dan131riley** [comment]
I've verified that the CMSSW MkFit plugin compiles and links with the latest two commits, apologies for not testing that before making the PR.  I could make the backport more targeted, but it will take more time.  (That we're still declaring `runBuildingTestPlexFV` in devel is a bug...)

**Comment by makortel** [comment]
Just to say it out loud, I'm thinking to remove the use of FullVector from CMSSW side quickly after the mkFit external gets updated (and update https://github.com/trackreco/cmssw as well).

**Pull request merged**
