### PR TITLE
Cmsswval dev

### PR DESCRIPTION
**Pull request by leonardogiannini**
starting the pull request to update the cmssw validation
added the following options under cmssw validation 
cmsswval_simmatch
cmsswval_simsignalmatch
cmsswval_nosimmatch
cmsswval_mkfiteff
cmsswval_mkfiteffsimsignal

the first three are for efficiency of CMSSW tracks to match mkfit tracks if the CMSSW track has a mached simTrack, a matched "signal" simTrack o no matched simTrack

the latter two are for mkfit tracks efficiency to match CMSSW tracks - this is done using the fakerate tree, which is not present by default. the first one uses all the mkfit built tracks while the second only the ones matching signal sim tracks.

### CODE REVIEW

**Comment by leonardogiannini** [comment]
I moved the script to test the cmssw validation to val_script

I also reviewed mario's script for comparing two configurations and added a similar one to compare the tracks that are different efficiency wise in the eff tree

**Comment by osschar** [comment]
Leonardo, do you want this merged?

**Comment by leonardogiannini** [comment]
No, I think it's not necessary and probably better to skim down the
validation as well, and add things later.

Leonardo

Il ven 8 gen 2021, 20:05 Matevž Tadel <notifications@github.com> ha scritto:

**Comment by leonardogiannini** [comment]
slim down (sorry for the typo)

anyway the concept is clear

Il giorno ven 8 gen 2021 alle ore 20:11 Leonardo GIANNINI <
leonardo.giannini@cern.ch> ha scritto:

**Comment by osschar** [comment]
Thanks, then I'll close it for now.

**Pull request closed without merging**
