### PR TITLE
Cluster size cuts

### PR DESCRIPTION
**Pull request by cerati**
Add option for cluster row size cut (iteration and layer-dependent), and turn it on for InitialStep.

Tested on initialStep within MTV:
http://uaf-8.t2.ucsd.edu/~cerati/plots_Sep16_ttbar_clshcut_PR/plots_initialStep.html

A PR to CMSSW with JSON updates will also be needed.

### CODE REVIEW

**Comment by cerati** [comment]
More MTV plots.

Muon samples (very low, low, high pT):
http://uaf-8.t2.ucsd.edu/~cerati/plots_Sep16_10muvlpt_clshcut_PR/plots_initialStep.html
http://uaf-8.t2.ucsd.edu/~cerati/plots_Sep16_10mulowpt_clshcut_PR/plots_initialStep.html
http://uaf-8.t2.ucsd.edu/~cerati/plots_Sep16_10mu_clshcut_PR/plots_initialStep.html

TTbar on top of PR357:
http://uaf-8.t2.ucsd.edu/~cerati/plots_Sep16_ttbar_clshcut_PR-PR357/plots_building_initialStep/hitsLayers.pdf

**Comment by cerati** [comment]
Code updated to use WP99.

Tests have been re-made on top of updates to PR357:
http://uaf-8.t2.ucsd.edu/~cerati/plots_Sep20_ttbar_clshcut_PR-PR357/plots_initialStep.html

Relevant plots for highPurityByOriginalAlgo:
image
image

WP99 was chosen taking into account the following values of "assocFraction" (faction of hits associated to the same simTrack), since WP95 does not really improve this metric (so the drop in number of hits is less motivated):
PR357: 0.97264939
PR357+clshcut99: 0.97300457
PR357+clshcut95: 0.97309722

**Comment by cerati** [comment]
@slava77 I have limited time these days, please let me know what is needed from me before merging

**Comment by slava77** [comment]
> @slava77 I have limited time these days, please let me know what is needed from me before merging

we talked yesterday about merging this PR (@osschar or @mmasciov to push the button).

After that, if time allows the idea is to check this WP99 applied in the other iterations in our set of 7 planned for release.

**Comment by cerati** [comment]
I tried to apply this to the 7 iterations, which should have been straightforward, but looks like something is broken. I need to find the time to debug what is going on. I'd suggest to pause and not merge this yet. PR357 may probably go ahead first

**Comment by cerati** [comment]
Ok, the issue was actually with the reference. The result of using WP99 on the 7 iters compared to iter0 only is here: http://uaf-8.t2.ucsd.edu/~cerati/plots_Sep23_ttbar_clshcut99_7iter/
Note that is still before 357 and 360 were merged.

**Comment by slava77** [comment]
> Ok, the issue was actually with the reference. The result of using WP99 on the 7 iters compared to iter0 only is here: http://uaf-8.t2.ucsd.edu/~cerati/plots_Sep23_ttbar_clshcut99_7iter/
> Note that is still before 357 and 360 were merged.

it looks like a good candidate to go in; apparently the outer iterations look better.

**Comment by cerati** [comment]
This is on top of current devel: http://uaf-8.t2.ucsd.edu/~cerati/plots_Sep24-devel_ttbar_clshcut99_7iter/
I am not sure it does much...

**Comment by slava77** [comment]
did #360 somehow drop the large clusters already?
I don't think #357 would affect the impact of this PR.

**Comment by osschar** [comment]
Yes, that's what I was saying on Wed, that most of large clusters likely come from tracks scraping the modules at low angles.

**Comment by cerati** [comment]
Closing as it does not bring improvements on top of other PRs.

**Pull request closed without merging**
