### PR TITLE
In bkfit, copy out final parameters from propagated or updated state based on the state of propagate-to-PCA.

### PR DESCRIPTION
**Pull request by osschar**

### CODE REVIEW

**Comment by osschar** [comment]
http://xrd-cache-1.t2.ucsd.edu/matevz/PKF/336-bkfit-copy-out/

**Comment by mmasciov** [comment]
MTV results in TTbar + PU50: http://uaf-10.t2.ucsd.edu/~mmasciov/MkFit_devs/MTV_PR336/
Differences between head and PR #336 appear to be marginal.

**Comment by slava77** [comment]
>  Differences between head and PR #336 appear to be marginal.

I was not expecting a significant effect on average; this is more about getting the logic correct.

**Comment by mmasciov** [comment]
If there are no objections, I'm going to click the 'merge' button on this PR.

**Pull request merged**
