### PR TITLE
Dup clean bins

### PR DESCRIPTION
**Pull request by leonardogiannini**
branch to check the code of duplicate cleaning

### CODE REVIEW

**Comment by leonardogiannini** [comment]
- Delta ctheta
image
- Delta phi 
image
Delta ctheta/ Delta phi of the track that are marked as duplicates with the current implementation 
plots only for the pixelLess iteration

**Comment by slava77** [comment]
> * Delta ctheta
>   image
> 
> *

which iteration is this?

**Comment by leonardogiannini** [comment]
> > * Delta ctheta
> >   image
> 
> which iteration is this?

pixelLess

**Comment by IHateLinus** [comment]
Looks very weird. What is it? 
I mean, how was it defined/computed?

**Comment by mmasciov** [comment]
Closing, as superseded by cms-sw/cmssw#37122.

**Pull request closed without merging**
